### ISSUE TITLE
Issue with readiness probe for sso

### ISSUE THREAD

**Issue by akoserwal** [integr8ly/integreatly-operator#296]
```
Readiness probe failed: { "probe.eap.dmr.EapProbe": "Error sending probe request: No JSON object could be decoded", "probe.eap.dmr.HealthCheckProbe": "Error sending probe request: No JSON object could be decoded" }
```
Defined in yaml:
```
readinessProbe:
        exec:
          command:
            - /bin/bash
            - '-c'
            - /opt/eap/bin/readinessProbe.sh
```
